### ISSUE TITLE
[NEW FEATURE] Provide a way to change bootloader's timeout from CLI

### ISSUE THREAD

**Issue by fleborne** [pollen-robotics/pyluos#106]
**What feature would you like to be included in Luos?**

Using pyluos' bootloader to reprogram a node that hosts a service that requires a *long* time to boot up can fail because of the `RESP_TIMEOUT`.
It could be useful to have a way to dynamically change this value in order to cope with services having a long starting time.

In my case, my service runs some checks on a motor before initializing Luos, and those tests take longer than a few seconds to run.

**Comment by fleborne** [comment]
In my case, this is no longer an issue. I now consider that it is a design problem if the service isn't able to handle Luos communication during its initialization.

**Comment by nicolas-rabault** [comment]
Ok, in our side we never had any problem regarding this.
Let's close this one for now.
