### ISSUE TITLE
[BUG] Increase wait state timing after asking statistics

### ISSUE THREAD

**Issue by JeromeGalan** [pollen-robotics/pyluos#141]
**Describe the bug**
First statistics are never received with some setups.
Linked to : https://github.com/Luos-io/luos_engine/issues/116

**How to reproduce the bug**
On first statistic asking.

**Additional context**
    def luos_statistics(self): 
        self._push_value('luos_statistics', "")
        time.sleep(0.3)   <--- this value should be greater

**Comment by fleborne** [comment]
I encountered this problem too.

Since I already have an open PR to improve statistics management, I added a commit that solves the current issue: https://github.com/Luos-io/Pyluos/pull/151/commits/745becf8a15801f87d6baee276a4cfe2158ed0b0
