### ISSUE TITLE
[BUG] Potential silent data drop?

### ISSUE THREAD

**Issue by fleborne** [pollen-robotics/pyluos#152]
**Describe the bug**

Looking at https://github.com/Luos-io/Pyluos/blob/master/pyluos/io/serial_io.py#L131, it seems to me that PyLuos may drop data silently if the queue becomes full.

If I'm correct, wouldn't it be better to consider this case as a real issue and warn the user, or even raise an exception?

**Comment by JeromeGalan** [comment]
Done in 2.6.0
